/**
 * matrix-market.test.js — the .mtx reader in file_handle.js.
 *
 * `readAsShipped` in ./matrix-market.js is a line-for-line copy of the parsing
 * inside `init()`, so asserting on it is asserting on the site.
 */

'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const { createEnvironment, installGraph, runPlain } = require('./harness');
const mm = require('./matrix-market');

test('every shipped matrix parses to well-formed 0-based indices', () => {
    const matrices = mm.listMatrices();
    assert.ok(matrices.length >= 20, 'the matrix library is present');

    for (const name of matrices) {
        const { n, edges } = mm.readAsShipped(mm.load(name));

        assert.ok(Number.isInteger(n) && n > 0, `${name}: dimension parsed`);
        for (const e of edges) {
            assert.ok(Number.isInteger(e.src) && e.src >= 0 && e.src < n,
                `${name}: row index ${e.src} in range`);
            assert.ok(Number.isInteger(e.tgt) && e.tgt >= 0 && e.tgt < n,
                `${name}: column index ${e.tgt} in range`);
        }
    }
});

test('the shipped parser agrees with a strict reader on every shipped matrix', () => {
    for (const name of mm.listMatrices()) {
        const shipped = mm.readAsShipped(mm.load(name));
        const strict = mm.readStrict(mm.load(name));

        assert.equal(shipped.n, strict.rows, `${name}: dimension`);
        assert.equal(shipped.symmetric, strict.symmetric, `${name}: symmetry flag`);

        const shippedPattern = new Set(shipped.edges.map(e => e.src + ',' + e.tgt));
        assert.deepEqual([...shippedPattern].sort(), [...strict.pattern()].sort(),
            `${name}: identical nonzero pattern`);
    }
});

test('the parser reports the column count, which bipgraph() now needs', () => {
    for (const name of mm.listMatrices()) {
        const shipped = mm.readAsShipped(mm.load(name));
        const strict = mm.readStrict(mm.load(name));
        assert.equal(shipped.n2, strict.cols, `${name}: column count`);
    }

    // Every shipped matrix happens to be square, but bipgraph is no longer
    // allowed to assume it — see bipartite.test.js.
    const rectangular = mm.readAsShipped([
        '%%MatrixMarket matrix coordinate real general',
        '2 3 2',
        '1 3 1',
        '2 2 1'
    ].join('\n'));
    assert.equal(rectangular.n, 2);
    assert.equal(rectangular.n2, 3);
});

test('nestedDissection4.mtx clears the module\'s 10-vertex guard', () => {
    // global_nd sets start_matrix = 'nestedDissection4.mtx', and the module
    // alerts and bails on anything with fewer than 10 vertices. If the default
    // matrix ever shrank, the module would be unusable on load.
    const strict = mm.readStrict(mm.load('nestedDissection4.mtx'));
    assert.ok(strict.rows >= 10, `has ${strict.rows} vertices`);
});

test('any number of comment lines is accepted, as the Matrix Market spec allows', () => {
    // The parser used to read dimensions from line 1 and entries from line 2
    // onwards, so a second '%' line shifted everything and produced NaN.
    const legal = [
        '%%MatrixMarket matrix coordinate real symmetric',
        '% Generated by some tool',
        '% and a second comment for good measure',
        '',
        '3 3 2',
        '1 1  1',
        '2 3  1'
    ].join('\n');

    const shipped = mm.readAsShipped(legal);
    const strict = mm.readStrict(legal);

    assert.equal(shipped.n, 3, 'dimensions read past the comments');
    assert.equal(shipped.n, strict.rows);
    // (1,1) is on the diagonal and is not mirrored; (2,3) is, so 3 edges.
    assert.deepEqual(shipped.edges, [
        { src: 0, tgt: 0 }, { src: 1, tgt: 2 }, { src: 2, tgt: 1 }
    ]);
});

test('any run of whitespace separates the fields', () => {
    // Entries used to be split on a single space, so an extra separator gave
    // an empty field and `parseInt('' - 1)` produced a plausible-looking -1.
    const messy = [
        '%%MatrixMarket matrix coordinate real general',
        '  3   3   2 ',
        '2  3  1',
        '1\t2\t1'
    ].join('\n');

    const shipped = mm.readAsShipped(messy);

    assert.equal(shipped.n, 3);
    assert.deepEqual(shipped.edges, [{ src: 1, tgt: 2 }, { src: 0, tgt: 1 }],
        'both entries parse, including the tab-separated one');

    const env = createEnvironment();
    installGraph(env, shipped.edges, 3, 'simple');
    const g = runPlain(env, 'currentg');
    // graph() is undirected, so vertex 1 picks up both (1,2) and (0,1).
    assert.deepEqual(g.vertices[1].edges.slice().sort((a, b) => a - b), [0, 2],
        'and the graph builds cleanly');
});

test('malformed or out-of-range entries are skipped instead of corrupting the graph', () => {
    const bad = [
        '%%MatrixMarket matrix coordinate real general',
        '3 3 3',
        '1 2 1',
        '9 9 1',      // out of range
        'oops'        // unparseable
    ].join('\n');

    const shipped = mm.readAsShipped(bad);
    assert.deepEqual(shipped.edges, [{ src: 0, tgt: 1 }],
        'only the one valid entry survives');

    const env = createEnvironment();
    installGraph(env, shipped.edges, 3, 'simple');
    assert.equal(runPlain(env, 'currentg').vertices.length, 3);
});

test('a trailing newline does not confuse the parser', () => {
    const withTrailing = [
        '%%MatrixMarket matrix coordinate real symmetric',
        '2 2 1',
        '1 2  1',
        ''
    ].join('\n');

    const shipped = mm.readAsShipped(withTrailing);
    assert.equal(shipped.edges.length, 2, 'one entry, mirrored because symmetric');
    assert.deepEqual(shipped.edges, [{ src: 0, tgt: 1 }, { src: 1, tgt: 0 }]);
});

test('symmetric files are expanded to both triangles, general files are not', () => {
    const sym = mm.readAsShipped(mm.load('cholesky.mtx'));
    const gen = mm.readAsShipped(mm.load('arrow-shaped2.mtx'));

    assert.equal(sym.symmetric, true);
    const offDiagonal = mm.readStrict(mm.load('cholesky.mtx'))
        .entries.filter(e => e.row !== e.col).length;
    const diagonal = sym.m - offDiagonal;
    assert.equal(sym.edges.length, 2 * offDiagonal + diagonal,
        'off-diagonal entries appear in both directions, the diagonal once');

    assert.equal(gen.symmetric, false);
    assert.equal(gen.edges.length, gen.m, 'general files are taken as given');
});

test('a symmetric file mirrors only its off-diagonal entries', () => {
    // (i,i) used to be emitted twice, since mirroring ignored the diagonal.
    const shipped = mm.readAsShipped(mm.load('cholesky.mtx'));
    const diagonalEdges = shipped.edges.filter(e => e.src === e.tgt);
    assert.equal(diagonalEdges.length, 6, 'six diagonal entries, each emitted once');

    const env = createEnvironment();
    installGraph(env, shipped.edges, 6, 'simple');
    const g = runPlain(env, 'currentg');

    for (let v = 0; v < 6; v++) {
        assert.equal(g.vertices[v].edges.filter(u => u === v).length, 0,
            `vertex ${v} has no self-loop at all`);
    }
});
